apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-nod-set
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-nod
  serviceName: "test-nod"
  template:
    metadata:
      labels:
        app: test-nod
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: test-nod
        image: 3rickmfs/nod:1.0.3
        ports:
        - containerPort: 5000 
        command:
          - /bin/sh
          - "-c"
          - "flask --app /home/nod/nod/nod_api run --host=0.0.0.0"

---

apiVersion: v1
kind: Service
metadata:
  name: test-node-headless-service
  labels:
    app: test-node-headless-service
spec:
  ports:
  - port: 5000
  clusterIP: None
  selector:
    app: test-nod

---

apiVersion: v1
kind: Service
metadata:
  name: test-nod-0-service
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    statefulset.kubernetes.io/pod-name: test-nod-set-0

---

apiVersion: v1
kind: Service
metadata:
  name: test-nod-1-service
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    statefulset.kubernetes.io/pod-name: test-nod-set-1

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-nod-0-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - secretName: tls-secret
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-nod-0-service
            port:
              number: 5000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-nod-1-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - secretName: tls-secret
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-nod-1-service
            port:
              number: 5000

---
