apiVersion: v1
kind: Service
metadata:
  name: test-nod-5-service
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    statefulset.kubernetes.io/pod-name: test-nod-set-5

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-nod-5-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - secretName: tls-secret
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-nod-5-service
            port:
              number: 5000

      - path: /save_neurons
        pathType: Prefix
        backend:
          service:
            name: test-nod-5-service
            port:
              number: 5000

      - path: /send_nod_inputs
        pathType: Prefix
        backend:
          service:
            name: test-nod-5-service
            port:
              number: 5000

---
